# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true

# Project
minecraft_version=1.21.1
enabled_platforms=neoforge
archives_base_name=XPlusContingameIME-NeoForge
mod_version=1.2.1-xplus
maven_group=org.thinkingstudio

# Common deps
architectury_version=13.0.6
kotlin_version=2.0.20

# NeoForge deps
neoforge_version=21.1.219
kotlinforforge_version=5.6.0

# Fabric deps
fabric_loader_version=0.17.3
fabric_version=0.115.6+1.21.1
fabric_language_kotlin_version=1.12.2+kotlin.2.0.20
cloth_config_version=15.0.140
rei_version=16.0.799
satin_version=2.0.0