modLoader="kotlinforforge"
loaderVersion="[5,)"

license="LGPL-3.0"

[[mods]]
modId="ingameime"
version="${version}"
displayName="ContingameIME-Neo"
description='''
An unofficial NeoForge port of XPlus-ContingameIME.
Unofficial continuation of ContingameIME, then further developed with reference to IngameIME,
Enable IME in FullScreen Minecraft.

'''
logoFile="icon.png"
authors="ThinkingStudio, TexTrue, Wybxc, Windmill_City, Wudji, sdy623"
credits="Hendrix-Shen"
displayURL="https://github.com/sdy623/XPlus-ContingameIME"

[[mixins]]
config="kitsuneime.neoforge.mixins.json"

[[dependencies.ingameime]]
modId="neoforge"
type="required"
versionRange="[20.6,21)"
ordering="NONE"
side="CLIENT"

[[dependencies.ingameime]]
modId="minecraft"
type="required"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="CLIENT"

[[dependencies.ingameime]]
modId="architectury"
type="required"
versionRange="[12,13)"
ordering="AFTER"
side="CLIENT"

[[dependencies.ingameime]]
modId="cloth_config"
type="required"
versionRange="[14,15)"
ordering="AFTER"
side="CLIENT"
